# excerpt_separator: "<!--more-->"
url: https://belindaterrisse.com/onlybridal
title: Belinda Terrisse portrait photography
description:
logo: style/images/sig.png
social:
  type: organization
  links: [ "https://www.facebook.com/belinda.terrisse", "https://www.instagram.com/belindaterrisse", "https://www.pinterest.com/belindaterrisse" ]

email_post_url: https://getsimpleform.com/messages?form_api_token=f4f995dca59e3f566b7d974bf51b46f4

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collage:
  - items: 1
    height: 62
    cols:
      - width: 100
  - items: 3
    height: 100
    cols:
      - width: 38
        height: 62, 38
      - width: 62
  - items: 3
    height: 100
    cols:
      - width: 62
      - width: 38
        height: 38, 62
  - items: 2
    height: 62
    cols:
      - width: 38
      - width: 62
  - items: 3
    height: 62
    cols:
      - width: 33
      - width: 33
      - width: 33
  - items: 2
    height: 62
    cols:
      - width: 62
      - width: 38
  - items: 3
    height: 100
    cols:
      - width: 38
        height: 62, 38
      - width: 62
  - items: 2
    height: 62
    cols:
      - width: 38
      - width: 62
  - items: 1
    height: 62
    cols:
      - width: 100
